<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Prescription - {{ $patient->medical_record_number }}</title>
    <style>
        body { font-family: sans-serif; line-height: 1.6; }
        .header { text-align: center; border-bottom: 2px solid #000; padding-bottom: 10px; margin-bottom: 20px; }
        .header h1 { margin: 0; color: #2c3e50; }
        .patient-info, .prescription-info { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        .patient-info th, .prescription-info th { text-align: left; padding: 8px; background-color: #f8f9fa; border: 1px solid #dee2e6; }
        .patient-info td, .prescription-info td { padding: 8px; border: 1px solid #dee2e6; }
        .section-title { font-size: 1.2rem; font-weight: bold; margin-bottom: 10px; color: #34495e; border-bottom: 1px solid #eee; }
        .footer { position: absolute; bottom: 30px; width: 100%; text-align: center; font-size: 0.8rem; color: #7f8c8d; }
    </style>
</head>
<body>
    <div class="header">
        <h1>MediConnect Clinic</h1>
        <p>123 Health Ave, Medical City | Phone: (555) 123-4567</p>
    </div>

    <div class="section-title">Patient Information</div>
    <table class="patient-info">
        <tr>
            <th>Name:</th>
            <td>{{ $patient->full_name }}</td>
            <th>MRN:</th>
            <td>{{ $patient->medical_record_number }}</td>
        </tr>
        <tr>
            <th>DOB:</th>
            <td>{{ $patient->date_of_birth->format('Y-m-d') }}</td>
            <th>Blood Group:</th>
            <td>{{ $patient->blood_group }}</td>
        </tr>
    </table>

    <div class="section-title">Medical Record Details</div>
    <table class="prescription-info">
        <tr>
            <th>Visit Date:</th>
            <td>{{ $record->visit_date->format('Y-m-d') }}</td>
        </tr>
        <tr>
            <th>Diagnosis:</th>
            <td>{{ $record->diagnosis }}</td>
        </tr>
        <tr>
            <th>Symptoms:</th>
            <td>{{ $record->symptoms }}</td>
        </tr>
    </table>

    <div class="section-title">Treatment Plan & Prescription</div>
    <p style="white-space: pre-wrap; padding: 15px; border: 1px solid #dee2e6; border-radius: 4px;">{{ $record->treatment_plan }}</p>

    <div style="margin-top: 50px;">
        <p><strong>Doctor:</strong> Dr. {{ $doctor->name }} ({{ $doctor->specialization ?? 'General Practitioner' }})</p>
        <p><strong>Date:</strong> {{ $date }}</p>
        <p style="margin-top: 30px; border-top: 1px dashed #000; width: 250px; padding-top: 10px;">Signature</p>
    </div>

    <div class="footer">
        Generated by MediConnect EHR System
    </div>
</body>
</html>
